name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [16]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Build Playground
        run: yarn dev:build

  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [16]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint
  
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [16]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Tests
        run: yarn test
  
  release-build:
    if: |
      github.event_name == 'push' &&
      !contains(github.event.head_commit.message, 'chore') &&
      !contains(github.event.head_commit.message, 'docs')

    needs:
      - lint
      - test
      - build

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies 👨🏻‍💻
        run: yarn --frozen-lockfile

      - name: Publish Package
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
