name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [16]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: pnpm install

      - run: pnpm dev:prepare

      - name: Build
        run: pnpm build

      - name: Build Playground
        run: pnpm dev:build

  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [16]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: pnpm install

      - run: pnpm dev:prepare

      - name: Lint
        run: pnpm lint
  
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [16]
        os: [ubuntu-latest]
      fail-fast: true

    timeout-minutes: 6

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: pnpm install

      - run: pnpm dev:prepare

      - name: Run Tests
        run: pnpm test -- --coverage --no-threads

      - uses: codecov/codecov-action@v3
  
  release-build:
    if: |
      github.event_name == 'push' &&
      !contains(github.event.head_commit.message, 'chore') &&
      !contains(github.event.head_commit.message, 'docs')

    needs:
      - lint
      - test
      - build

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - run: yes | npx bumpp package.json
